#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#


apiVersion: galasa.dev/v1alpha
kind: Release
metadata:
  name: galasa-release


release:
  version: 0.38.0



external:
  bundles:
  - group: com.google.code.gson
    artifact: gson
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: com.sun.xml.bind
    artifact: jaxb-osgi
    obr: true

  - group: commons-codec
    artifact: commons-codec
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: commons-collections
    artifact: commons-collections
    obr: true
    mvp: true
    isolated: true

  - group: commons-io
    artifact: commons-io
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: commons-lang
    artifact: commons-lang
    obr: true
    mvp: true
    isolated: true

  # commons-logging is not included in the OBR because it is exported in
  # the log4j2.bridge bundle and that bundle is directly installed into 
  # the Felix framework at runtime.
  # Adding it into the OBR causes run logs to no longer be captured correctly!
  - group: commons-logging
    artifact: commons-logging
    obr: false
    bom: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.platform
    obr: false
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.com.jcraft.jsch
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.com.auth0.jwt
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.gson
    obr: true
    bom: true
    mvp: true
    isolated: true

  - artifact: dev.galasa.wrapping.httpclient-osgi
    obr: true
    bom: true
    isolated: true
    mvp: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.io.grpc.java
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.io.kubernetes.client-java
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.protobuf-java
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.jta
    obr: true
    mvp: true
    isolated: true

  - artifact: dev.galasa.wrapping.velocity-engine-core
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.kafka.clients
    obr: true
    mvp: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient
    obr: true
    mvp: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_common
    obr: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_hotspot
    obr: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_httpserver
    obr: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_tracer_common
    obr: true
    mvp: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_tracer_otel
    obr: true
    mvp: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_tracer_otel_agent
    obr: true
    mvp: true
    isolated: true

  - group: jakarta.activation
    artifact: jakarta.activation-api
    obr: true
    mvp: true
    isolated: true

  - group: jakarta.xml.bind
    artifact: jakarta.xml.bind-api
    obr: true
    mvp: true
    isolated: true

  - group: javax.validation
    artifact: validation-api
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: org.apache.bcel
    artifact: bcel
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.commons
    artifact: commons-collections4
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.commons
    artifact: commons-compress
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.commons
    artifact: commons-lang3
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: org.apache.derby
    artifact: derbyclient
    obr: true

  - group: org.apache.felix
    artifact: org.apache.felix.configadmin
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.fileinstall
    obr: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.gogo.command
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.gogo.runtime
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.gogo.shell
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.http.jetty
    obr: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.http.servlet-api
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.httpcomponents
    artifact: httpcore-osgi
    obr: true
    bom: true
    isolated: true
    mvp: true

  - group: org.apache.logging.log4j
    artifact: log4j-api
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.logging.log4j
    artifact: log4j-core
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.logging.log4j
    artifact: log4j-slf4j-impl
    obr: true
    mvp: true
    isolated: true

  - group: org.assertj
    artifact: assertj-core
    version: 3.11.1
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: org.bouncycastle
    artifact: bcpkix-jdk18on
    obr: true

  - group: org.bouncycastle
    artifact: bcprov-jdk18on
    obr: true

  - group: org.bouncycastle
    artifact: bcutil-jdk18on
    obr: true

  - group: org.osgi
    artifact: org.osgi.service.component.annotations
    bom: true

  - group: org.slf4j
    artifact: slf4j-api
    version: 1.7.30
    obr: true
    mvp: true
    isolated: true

  - group: org.yaml
    artifact: snakeyaml
    obr: true
    isolated: true
    mvp: true
